services:
  - type: web
    name: anime-caption-bot
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PORT
        value: 8080
      - key: ENABLE_HEALTH_CHECK
        value: true
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: anime-caption-bot
          property: host
    autoDeploy: true
    buildFilter:
      paths:
        - main.py
        - requirements.txt
        - Dockerfile
